geometry:
  aggregation: last

correlation:
  n_perm: 0
  pairs_csv:    "code/results/eclektic_law_correlations/{model}/pairs.csv"
  results_csv:  "code/results/eclektic_law_correlations/{model}/correlation_results.csv"
  lollipop_dir: "plots/eclektic_law_correlations/{model}/lollipop"
  heatmaps_dir: "plots/eclektic_law_correlations/{model}/heatmaps"

filter:
  correlations: [spearman, pearson]
