datasets:
  - name: "English"
    path: "HuggingFaceFW/fineweb"
    subset: "sample-10BT"
  - name: "Chinese"
    path: "HuggingFaceFW/fineweb-2"
    subset: "cmn_Hani"
  - name: "Indonesian"
    path: "HuggingFaceFW/fineweb-2"
    subset: "ind_Latn"
  - name: "Italian"
    path: "HuggingFaceFW/fineweb-2"
    subset: "ita_Latn"
  - name: "Swahili"
    path: "HuggingFaceFW/fineweb-2"
    subset: "swh_Latn"
  - name: "Spanish"
    path: "HuggingFaceFW/fineweb-2"
    subset: "spa_Latn"
  - name: "German"
    path: "HuggingFaceFW/fineweb-2"
    subset: "deu_Latn"
  - name: "Hindi"
    path: "HuggingFaceFW/fineweb-2"
    subset: "hin_Deva"
  - name: "Arabic"
    path: "HuggingFaceFW/fineweb-2"
    subset: "arb_Arab"
  - name: "Turkish"
    path: "HuggingFaceFW/fineweb-2"
    subset: "tur_Latn"
  - name: "Vietnamese"
    path: "HuggingFaceFW/fineweb-2"
    subset: "vie_Latn"
  - name: "Japanese"
    path: "HuggingFaceFW/fineweb-2"
    subset: "jpn_Jpan"