datasets:
  - name: "English"
    path: "openlanguagedata/flores_plus"
    subset: "eng_Latn"
    split: "devtest"
  - name: "Chinese"
    path: "openlanguagedata/flores_plus"
    subset: "cmn_Hans"
    split: "devtest"
  - name: "French"
    path: "openlanguagedata/flores_plus"
    subset: "fra_Latn"
    split: "devtest"
  - name: "Indonesian"
    path: "openlanguagedata/flores_plus"
    subset: "ind_Latn"
    split: "devtest"
  - name: "Italian"
    path: "openlanguagedata/flores_plus"
    subset: "ita_Latn"
    split: "devtest"
  - name: "Swahili"
    path: "openlanguagedata/flores_plus"
    subset: "swh_Latn"
    split: "devtest"
  - name: "Spanish"
    path: "openlanguagedata/flores_plus"
    subset: "spa_Latn"
    split: "devtest"
  - name: "German"
    path: "openlanguagedata/flores_plus"
    subset: "deu_Latn"
    split: "devtest"
  - name: "Hindi"
    path: "openlanguagedata/flores_plus"
    subset: "hin_Deva"
    split: "devtest"
  - name: "Arabic"
    path: "openlanguagedata/flores_plus"
    subset: "arb_Arab"
    split: "devtest"
  - name: "Turkish"
    path: "openlanguagedata/flores_plus"
    subset: "tur_Latn"
    split: "devtest"
  - name: "Vietnamese"
    path: "openlanguagedata/flores_plus"
    subset: "vie_Latn"
    split: "devtest"
  - name: "Japanese"
    path: "openlanguagedata/flores_plus"
    subset: "jpn_Jpan"
    split: "devtest"